name: flutter_audio_recorder3_example
description: Demonstrates how to use the flutter_audio_recorder3 plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  file: ^6.1.4
  audioplayers: ^1.1.1

  flutter_audio_recorder3:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true